### ISSUE TITLE
TouchableHighlight onPress events do not work

### ISSUE THREAD

**Issue by aj9045** [maxs15/react-native-modalbox#21] opened 2015-11-24 17:37 UTC
Nice work on the modal!  I'm on Android (emulator) and I was going to use the modal for buttons (like delete).  TouchableHighlight's onPress does not work inside the modal it seems.

**Comment by maxs15** [comment] 2015-11-25 22:03
Did you try with the last version ?

**Comment by vitorhorta** [comment] 2015-11-26 00:07
@aj9045 Did you try positioning your modal on top? It works great for me this way (using the last version).

**Comment by easyfan** [comment] 2015-12-01 06:19
Confirm, I got this issue on my local env with modal box 1.2.4. More specifications, similar as @vitorhorta suggested, with setting position to "top", everything working well. But with setting position to "center" or "bottom", the issue happened.

**Comment by maxs15** [comment] 2015-12-01 17:18
Thanks for the feedback @easyfan, I still can't reproduce this behavior..
Did you get this issue using the example app ?
Could you give me more informations, android or ios, os version, emulator or not..

Thanks

**Comment by easyfan** [comment] 2015-12-07 09:11
hi, @maxs15, yes I got this issue with using the example app.

I slightly changed you example codes for showing the issue directly:
```
  onTestBtn: function() {
    console.log('test click.');
  },

  render: function() {

    var BContent = <Button onPress={this.closeModal5} style={[styles.btn, styles.btnModal]}>X</Button>;

    return (
      <View style={styles.wrapper}>
        <Button onPress={this.openModal1} style={styles.btn}>Basic modal</Button>
        <Button onPress={this.openModal2} style={styles.btn}>Position top</Button>
        <Button onPress={this.openModal3} style={styles.btn}>Position centered + backdrop + disable</Button>
        <Button onPress={this.openModal4} style={styles.btn}>Position bottom + backdrop</Button>
        <Button onPress={this.openModal5} style={styles.btn}>Backdrop + backdropContent</Button>

        <Modal style={[styles.modal, styles.modal1]} ref={"modal1"} onClosed={this.onClose} onOpened={this.onOpen} onClosingState={this.onClosingState}>
          <Text style={styles.text}>Basic modal</Text>
        </Modal>

        <Modal style={[styles.modal, styles.modal2]} backdrop={false}  position={"top"} ref={"modal2"}>
          <Text style={[styles.text, {color: "white"}]}>Modal on top</Text>
        </Modal>

        <Modal style={[styles.modal, styles.modal3]} position={"center"} ref={"modal3"} isDisabled={this.state.isDisabled}>
          <Text style={styles.text}>Modal centered</Text>
          <Button onPress={this.toggleDisable} style={styles.btn}>Disable ({this.state.isDisabled ? "true" : "false"})</Button>
        </Modal>

        <Modal style={[styles.modal, styles.modal4]} position={"bottom"} ref={"modal4"}>
          <Text style={styles.text}>Modal on bottom with backdrop</Text>
        </Modal>

        <Modal isOpen={this.state.isOpen} onClosed={this.closeModal5} style={[styles.modal, styles.modal4]} position={"center"} backdropContent={BContent}>
          <Text style={styles.text}>Modal with backdrop content</Text>
          <Button onPress={this.onTestBtn} style={styles.btn}>test button press</Button>
        </Modal>
      </View>
    );
  }
```
Within debug mode, such log message 'test click.' never shown, whatever how many times the button "test button press" clicked.

**Comment by devjv** [comment] 2015-12-18 14:08
+1

**Comment by maxs15** [comment] 2015-12-18 16:15
Ok great, because I wasn't able to reproduce it either :D
I'm closing this issue for now

**Closed by maxs15** 2015-12-18 16:15 UTC
