### ISSUE TITLE
 Animated: `useNativeDriver` was not specified. This is a required option and must be explicitly set to `true` or `false`

### ISSUE THREAD

**Issue by virtualvivek** [maxs15/react-native-modalbox#313] opened 2020-04-10 13:11 UTC
## ModalBox 
Showing YellowBox Warning Should use `useNativeDriver` in my current react-native 
## Using react-native release - "16.13.1"

**Comment by orzhtml** [comment] 2020-04-15 09:01
Duplicate of #312

**Comment by joaovictorcosta** [comment] 2020-04-18 14:10
Estou com o mesmo problema

**Comment by joaovictorcosta** [comment] 2020-04-18 14:11
Me too have this problem!

**Comment by edritech93** [comment] 2020-04-20 02:08
same for me

**Comment by tischenkoa** [comment] 2020-04-21 20:36
fixed this problem
https://github.com/maxs15/react-native-modalbox/pull/315/commits/50979244a4cab2488c38f5bae43ce20d7a915171

**Comment by cedricjacobs** [comment] 2020-04-24 09:13
When I integrate this solution in my code, I get an error when I try to implement swipeToClose modals. 

![Simulator Screen Shot - iPhone 11 - 2020-04-24 at 11 12 38](https://user-images.githubusercontent.com/12216776/80195694-87933800-861c-11ea-8be0-b87038200a5f.png)
.

**Comment by ghasemikasra39** [comment] 2020-05-11 16:43
Same here

**Comment by chahinaghrim** [comment] 2020-05-13 08:28
same for me

**Comment by tmoutinho** [comment] 2020-09-15 15:08
Please merge it in master.

**Comment by maxs15** [comment] 2020-10-04 22:02
Fix deployed in 2.0.1

**Closed by maxs15** 2020-10-04 22:02 UTC

**Comment by jorgegvallejo** [comment] 2020-11-10 17:20
> Edit: this can be resolved by adjusting it to:
> ` const animEvt = Animated.event([null, {customY: position}], {useNativeDriver: false});`

I tried this, the warning is gone, but now I get a different error:
`TypeError: animEvt is not a function. (In 'animEvt(evt, state)', 'animEvt' is an instance of AnimatedEvent)`
